name: template
services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

# app:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   container_name: nest-example
#   environment:
#     - DATABASE_URL=postgresql://postgres:postgres@db:5432/template?schema=public
#   ports:
#     - 3333:3333
#   volumes:
#     - .:/usr/src/app
#   depends_on:
#     - database

volumes:
  postgres_data: